---
# ANSIBLE_NETWORK_GROUP_MODULES=sonic ansible-playbook playbooks/common_examples/fmcli_ports_config.yaml -i inventory/nvidia_host -vvv
- name: "FMCLI Ports Configuration "
  hosts: leafs 
  gather_facts: no
  connection: network_cli
  collections:
    - aviznetworks.sonic_fmcli
  
  tasks:

  - name: host_var group_var test
    sonic_vlan:
      action: vlanconf                             
      vlanid: "{{ vlan.vlan100 }}, {{ vlan.vlan200 }}"
      interface: "{{ interface.inf1 }}" 
      vlanmode: 'trunk'



  # - name: SONiC port configuration
  #   sonic_ports:
  #     interface: 'Ethernet32'                  
  #     mtu: 9000                                
  #     enable: true                             
  #     description: "fmcli description_eth32"   
  #     wait_for:                                
  #       - result[1] contains config-if
  #       - result[6] contains "Saving Configuration"
  #     match: any 
  #   register: cmd_op
 
  - name: Configure vlan
    sonic_vlan:
      action: vlanconf                             
      vlanid: '100,200,300'                 

  # - name: Configure trunk port on the physical interface
  #   sonic_vlan:
  #     vlanid: '200,300,400'
  #     interface: 'Ethernet32'                  
  #     vlanmode: 'trunk' 


  # - name: Unconfigure trunk port on the physical interface
  #   sonic_vlan:   
  #     action: accesstrunkunconf                            
  #     vlanid: '100,200,300'
  #     interface: 'Ethernet32'                 
  #     vlanmode: 'trunk'    

  # - name: Configure access port on the physical interface
  #   sonic_vlan:
  #     action: accesstrunkconf                               
  #     vlanid: '100'
  #     interface: 'Ethernet32'                  
  #     vlanmode: 'access' 

  # - name: Unconfigure access and trunk port on the physical interface
  #   sonic_vlan:   
  #     action: accesstrunkunconf                            
  #     vlanid: '100'
  #     interface: 'Ethernet32'                 
  #     vlanmode: 'access'

  # - name: Unconfigure vlans on the device
  #   sonic_vlan:   
  #     action: vlanunconf                            
  #     vlanid: '100,200,300'

  # - name: unconfigure ethernet port 
  #   sonic_vlan:
  #     action: unconfigure
  #     interface: 'Ethernet32' 

  